config/routes.rb
Banquetx::Engine.routes.draw do
  resources :banquets do
    collection do
      get :search
      get :search_results
    end
  end
  resources :menus do
    collection do
      get :search
      get :search_results
    end
  end
  
  root :to => 'banquets#index'
end

app/models/banquetx/banquet.rb
module Banquetx
  class Banquet < ActiveRecord::Base
    
    attr_accessor :host_name, :last_updated_by_name, :approved_by_name, :replied_by_name
    
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :host, :class_name => 'Authentify::User'
    belongs_to :replied_by, :class_name => 'Authentify::User'
    belongs_to :approved_by, :class_name => 'Authentify::User'  
      
    validates :host_id, :banquet_date, :banquet_time, :presence => true
    validates :host_id, :numericality => {:greater_than => 0, :only_integer => true}
    validates :banquet_time, :uniqueness => {:scope => [:host_id, :banquet_date], :case_sensitive => false, :message => I18n.t('Duplidate Host!')}
    validates :replied_by_id, :numericality => {:greater_than => 0, :only_integer => true}, :if => 'replied_by_id.present?'        
    validates :approved_by_id, :numericality => {:greater_than => 0, :only_integer => true}, :if => 'approved_by_id.present?'  
    validates :category_id, :numericality => {:greater_than => 0, :only_integer => true}, :if => 'category_id.present?'       
    validate :dynamic_validate 
    
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate_banquet', 'banquetx_banquet')
      eval(wf) if wf.present?
    end
  end
end

app/models/banquetx/menu.rb
module Banquetx
  class Menu < ActiveRecord::Base
    attr_accessor :course_name, :last_updated_by_name, :category_name
    
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :course, :class_name => Banquetx.banquet_course_class.to_s
    belongs_to :banquet, :class_name => 'Banquetx::Banquet'
    #belongs_to :approved_by, :class_name => 'Authentify::User'  
      
    validates :banquet_id, :course_id, :qty, :presence => true, :numericality => {:greater_than => 0, :only_integer => true}    
    validates :course_id, :uniqueness => {:scope => :banquet_id, :message => I18n.t('Duplidate Dish Course!')}
    #validates :approved_by_id, :numbericality => {:greater_than => 0, :only_integer => true}, :if => 'approved_by_id.present?'        
    validate :dynamic_validate 
    
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate_menu', 'banquetx_banquet')
      eval(wf) if wf.present?
    end
  end
end

app/controllers/banquetx/application_controller.rb
module Banquetx
  class ApplicationController < ::ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    include Searchx::SearchHelper
    
    #before_action :require_signin
    before_action :max_pagination 
    before_action :check_access_right 
    before_action :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_action :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right
    before_action :view_in_config?
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination')
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
  end
end

app/controllers/banquetx/banquets_controller.rb
require_dependency "banquetx/application_controller"

module Banquetx
  class BanquetsController < ApplicationController
    before_action :require_employee
    before_action :load_records
        
    def index
      @title = t('Banquets')
      @banquets = params[:banquetx_banquets][:model_ar_r]  #returned by check_access_right
      @banquets = @banquets.where(category_id: @category_id) if @category_id
      @banquets = @banquets.where(host_id: @host.id) if @host
      @banquets = @banquets.page(params[:page]).per_page(@max_pagination) 
      @erb_code = find_config_const('banquet_index_view', 'banquetx')
    end
  
    def new
      @title = t('New Banquet')
      @banquet = Banquetx::Banquet.new()
      @erb_code = find_config_const('banquet_new_view', 'banquetx')
    end
  
    def create
      @banquet = Banquetx::Banquet.new(new_params)
      @banquet.last_updated_by_id = session[:user_id]
      @banquet.booked_by_id = session[:user_id]
      if @banquet.save
        redirect_to URI.escape(SUBURI + "/view_handler?index=1&url=#{menus_path(banquet_id: @banquet.id)}&msg=Successfully Saved!")
      else
        @erb_code = find_config_const('banquet_new_view', 'banquetx')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update Banquet')
      @banquet = Banquetx::Banquet.find_by_id(params[:id])
      @erb_code = find_config_const('banquet_edit_view', 'banquetx')
    end
  
    def update
      @banquet = Banquetx::Banquet.find_by_id(params[:id])
      @banquet.last_updated_by_id = session[:user_id]
      if @banquet.update_attributes(edit_params)
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Successfully Updated!")
      else
        @erb_code = find_config_const('banquet_edit_view', 'banquetx')
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = t('Banquet Info')
      @banquet = Banquetx::Banquet.find_by_id(params[:id])
      @erb_code = find_config_const('banquet_show_view', 'banquetx')
    end
    
    def destroy
      Banquetx::Banquet.delete(params[:id])
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Successfully Deleted!")
    end
    
    protected
    
    def load_records
      @host = Authentify::User.find_by_id(params[:host_id].to_i) if params[:host_id].present?
      @host = Authentify::User.find_by_id(Banquetx::Banquet.find_by_id(params[:id].to_i).host_id) if params[:id].present?
      @category_id = params[:category_id].to_i if params[:category_id].present?
    end
    
    private
    
    def new_params
      params.require(:banquet).permit(:banquet_date, :banquet_time, :host_id, :number_of_atendee, :about, :note, :about_atendee, :drink, :less_sodium,
                     :less_fat, :avoid_certain_food, :wf_state, :how_many_table)
    end

    def edit_params
      params.require(:banquet).permit(:banquet_date, :banquet_time, :host_id, :number_of_atendee, :about, :note, :about_atendee, :drink, :less_sodium,
                     :less_fat, :avoid_certain_food, :wf_state, :kitchen_replied, :kitchen_replied_time, :replied_by_id, :approved, :approved_time,
                     :approved_by_id, :feedback, :star_rating, :how_many_table, :cancelled)
    end

  end
end

app/controllers/banquetx/menus_controller.rb
require_dependency "banquetx/application_controller"

module Banquetx
  class MenusController < ApplicationController
    before_action :require_employee
    before_action :load_record
        
    def index
      @title = t('Dishes')
      @menus = params[:banquetx_menus][:model_ar_r]  #returned by check_access_right
      @menus = @menus.where(banquet_id: @banquet.id) if @banquet
      @menus = @menus.where(course_id: @course.id) if @course
      @menus = @menus.page(params[:page]).per_page(@max_pagination) 
      @erb_code = find_config_const('menu_index_view', 'banquetx')
    end
  
    def new
      @title = t('New Dish')
      @menu = Banquetx::Menu.new()
      @erb_code = find_config_const('menu_new_view', 'banquetx')
      @js_erb_code = find_config_const('menu_new_js_view', 'banquetx')
    end
  
    def create
      @menu = Banquetx::Menu.new(new_params)
      @menu.last_updated_by_id = session[:user_id]
      if @menu.save
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Successfully Saved!")
      else
        @erb_code = find_config_const('menu_new_view', 'banquetx')
        @js_erb_code = find_config_const('menu_new_js_view', 'banquetx')
        @banquet = Banquetx::Banquet.find_by_id(params[:menu][:banquet_id])
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update Dish')
      @menu = Banquetx::Menu.find_by_id(params[:id])
      @erb_code = find_config_const('menu_edit_view', 'banquetx')
      @js_erb_code = find_config_const('menu_edit_js_view', 'banquetx')
    end
  
    def update
      @menu = Banquetx::Menu.find_by_id(params[:id])
      @menu.last_updated_by_id = session[:user_id]
      if @menu.update_attributes(edit_params)
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Successfully Updated!")
      else
        @erb_code = find_config_const('menu_edit_view', 'banquetx')
        @js_erb_code = find_config_const('menu_edit_js_view', 'banquetx')
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = t('Dish Info')
      @menu = Banquetx::Menu.find_by_id(params[:id])
      @erb_code = find_config_const('menu_show_view', 'banquetx')
    end
    
    def destroy
      Banquetx::Menu.delete(params[:id])
      redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Successfully Deleted!")
    end
    
    protected
    
    def load_record
      @banquet = Banquetx::Banquet.find_by_id(params[:banquet_id]) if params[:banquet_id].present?
      @banquet = Banquetx::Banquet.find_by_id(Banquetx::Menu.find_by_id(params[:id]).banquet_id) if params[:id].present?
      @course = Banquetx.banquet_course_class.find_by_id(params[:course_id].to_i) if params[:course_id].present?
      @course = Banquetx.banquet_course_class.find_by_id(Banquetx::Menu.find_by_id(params[:id].to_i).course_id) if params[:id].present?
    end
    
    private
    
    def new_params
      params.require(:menu).permit(:banquet_id, :course_id, :less_sodium, :less_fat, :brief_note, :less_hot, :qty, :wf_state)
    end

    def edit_params
      params.require(:menu).permit(:course_id, :less_sodium, :less_fat, :brief_note, :less_hot, :qty, :wf_state, :approved)
    end

  end
end

app/helpers/banquetx/application_helper.rb
module Banquetx
  module ApplicationHelper
  end
end

app/helpers/banquetx/banquets_helper.rb
module Banquetx
  module BanquetsHelper
  end
end

app/helpers/banquetx/menus_helper.rb
module Banquetx
  module MenusHelper
  end
end

app/views/banquetx/banquets/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
  <% else %>
<div class="container">
  <div class="page-header clearfix">
    <div class="pull-left">
    <h2><%=@title%></h2>
    </div>
  </div>
<%= simple_form_for @banquet, html: { class: 'form-horizontal col-sm-' + BUTTONS_CLS['form-span#'] },
    wrapper: :horizontal_form,
    wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean } do |f| %>
  
  <div class="form-inputs"> 
      <%= f.input :banquet_date, :label => t('Date'), :as => :string %>
	  <%= f.input :banquet_time, :label => t('Time'), :collection => Authentify::AuthentifyUtility.find_config_const('time_interval', 'banquetx').split(',').map(&:strip), include_blank: true %>
	  <%= f.input :host_id, :label => t('Host'), :collection => Authentify::User.joins(:user_levels => :sys_user_group).where.not('authentify_sys_user_groups.user_group_name = ?', 'admin'), :include_blank => true %>
	  <%= f.input :about, :label => t('About') %>
	  <%= f.input :number_of_atendee, :label => t('Atendee#') %>
	  <%= f.input :note, :label => t('Note'), :input_html => {:rows => 3} %>
	  
	  <div class="btn-toolbar"> 
              <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
              <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>
      </div> 
  
  </div>
 
<% end %>

</div>

<% end %>

app/views/banquetx/banquets/_form_list.html.erb
 <% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
  <% else %>
<div class="pagination"><%= will_paginate models %></div>
<div class="container-fluid">
        <div class="page-header clearfix">
          <div class="pull-left">
            <h2><%=@title%></h2>
          </div>
        </div>
      <table class="table table-hover">
              <thead>
		<tr>
			<th>#</th>
			<th><%= t('Date') %></th>
			<th><%= t('Host') %></th>
			<th><%= t('# of Atendee') %></th>
            <th><%= t('# of Dishes') %></th>
			<th><%= t('About') %></th>
			<th></th>
            <th></th>
	  	</tr>
                </thead>
                <tbody>
		<% models.each do |r| %>
		  <tr>
		  	<% if has_action_right?('show', params[:controller], r) %>
		  	  <td><%= link_to r.id, SUBURI + "/view_handler?index=1&url=#{banquet_path(r)}"  %></td>
		  	<% else %>
		  	  <td><%= r.id %></td>
		  	<% end %>
		  	<td><%= prt(r, :banquet_date).strftime('%Y/%m/%d') %>:<%=prt(r, :banquet_time)%></td>
		  	<td><%= prt(r, 'host.name') %></td> 
			<td><%= prt(r, :number_of_atendee) %></td> 
			<td><%= Banquetx::Menu.where(banquet_id: r.id).count %></td>
			<td><%= prt(r, :about) %></td>
			<%  if has_action_right?('index', 'banquetx_menus') %> 
			  <td><%= link_to t('Menu'), SUBURI + "/view_handler?index=1&url=#{CGI::escape menus_path(banquet_id: r.id, parent_record_id: r.id, parent_resource: params[:controller])}", :class => BUTTONS_CLS['action'] %></td>
			<% end %>
			<%  if has_action_right?('update', params[:controller], r) %>   
              <td><%= link_to t('Edit'), SUBURI + "/view_handler?index=1&url=#{CGI::escape edit_banquet_path(r)}", :class => BUTTONS_CLS['action'] %></td>
            <% end %>
		  </tr>
		<% end %>
	    </tbody>
       </table>
	
	<div class="btn-toolbar">
	   	<%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
	    <%= link_to t('New Banquet'), SUBURI + "/view_handler?index=1&url=#{CGI.escape new_banquet_path()}", :class => BUTTONS_CLS['action']  if has_action_right?('create', params[:controller]) %>
	</div>
</div>
	
<% end %>
	

app/views/banquetx/banquets/_form_new.html.erb
<% if @view_in_config && @erb_code  %>
  <%= render inline: @erb_code %>
  
  <% else %>
<div class="container">
  <div class="page-header clearfix">
    <div class="pull-left">
    <h2><%=@title%></h2>
    </div>
  </div>
<%= simple_form_for @banquet, html: { class: 'form-horizontal col-sm-' + BUTTONS_CLS['form-span#'] },
    wrapper: :horizontal_form,
    wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  } do |f| %>
  
    <div class="form-inputs">  
	  <%= f.input :banquet_date, :label => t('Date'), :as => :string %>
	  <%= f.input :banquet_time, :label => t('Time'), :collection => Authentify::AuthentifyUtility.find_config_const('time_interval', 'banquetx').split(',').map(&:strip), include_blank: true %>
	  <%= f.input :host_id, :label => t('Host'), :collection => Authentify::User.joins(:user_levels => :sys_user_group).where.not('authentify_sys_user_groups.user_group_name = ?', 'admin'), :include_blank => true %>
	  <%= f.input :about, :label => t('About') %>
	  <%= f.input :number_of_atendee, :label => t('Atendee#') %>
	  <%= f.input :note, :label => t('Note'), :input_html => {:rows => 3} %>
	  
	  <div class="btn-toolbar" >
            <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
            <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>    
      </div> 

  </div>
 
<% end %>

</div>
<% end%>

app/views/banquetx/banquets/create.html.erb
<h4>Projects#create</h4>
<p>Find me in app/views/task_definitions/create.html.erb</p>

app/views/banquetx/banquets/edit.html.erb
<div id="main_body">
 
<%= render 'form'  %>
 
</div>
  
 

app/views/banquetx/banquets/index.html.erb
<div id="main_body">
	 
	<%= render partial: 'form_list', locals: {models: @banquets} %>
 
</div>

app/views/banquetx/banquets/new.html.erb
<div id="main_body">

<%= render 'form_new' %>

</div>

app/views/banquetx/banquets/show.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
  <% else %>
<div id="main_body">
<div class="container">
  <div class="page-header clearfix">
      <div class="pull-left">
        <h2><%=@title%></h2>
      </div>
    </div>
 <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
         <b><%= t('Banquet Time') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
         <%= @banquet.banquet_date.strftime('%Y/%m/%d') %>@<%=@banquet.banquet_time%>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
             <b><%= t('Host') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
           <%= @banquet.host.name %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
         <b><%= t('About') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
           <%= @banquet.about %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
          <b><%= t('Atendee') %></b>
     </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
            <%= @banquet.number_of_atendee %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
           <b><%= t('Note') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
           <%= @banquet.note %>
    </div>
 </div>
  <div class="row">
    <div class="col-sm-<%=BUTTONS_CLS['left-span#']%> form-group">
            <b><%= t('Last Updated By') %></b>
    </div>
    <div class="col-sm-<%=BUTTONS_CLS['right-span#']%> form-group">
            <%= @banquet.last_updated_by.name %>
    </div>
 </div>
  
   <div class="btn-toolbar">
     <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
    </div>  
 </div>
	
</div>
<% end %>

app/views/banquetx/banquets/update.html.erb
<h1>EventTasks#update</h1>
<p>Find me in app/views/event_taskx/event_tasks/update.html.erb</p>